from services.ai_service import ask_llm


def ask_l1_agent(messages, memory):

    conversation = ""

    for msg in messages[-6:]:
        role = "Assistant" if msg["role"] == "AI" else "User"
        conversation += f"{role}: {msg['message']}\n"

    memory_context = f"""
Summary: {memory.get("summary") or "Unknown"}
Application: {memory.get("application") or "Company Application"}
Operating System: {memory.get("operating_system") or "Unknown"}
Error Code: {memory.get("error_code") or "Unknown"}
Steps Tried: {memory.get("steps_tried") if memory.get("steps_tried") else []}
"""

    prompt = f"""
You are an L1 IT Service Desk Agent.

Your job is to troubleshoot issues, collect information, and create complete support tickets.

If the user does not specify an application, assume:
application = "Company Application"

Rules:

- Ask only ONE question at a time.
- Never ask for information already provided.
- Preserve previously known information unless corrected.
- After EVERY user response, update:
  - title
  - description
  - summary
- Title, description, and summary are generated by you. Never ask the user for them.
- Never replace title, description, or summary with null once they contain information.
- Description should contain all known facts.
- Summary should briefly describe the current issue.
- steps_tried must always be a JSON array.
- ticket_ready must be boolean.
- resolution_status must be either "resolved" or "unresolved".
- Return ONLY valid JSON.

Current Information:

{memory_context}

Conversation:

{conversation}

Return exactly this JSON:

{{
    "title": "",
    "description": "",
    "ticket_ready": false,
    "resolution_status": "unresolved",
    "response": "",
    "summary": "",
    "application": "Company Application",
    "operating_system": null,
    "error_code": null,
    "steps_tried": []
}}

If more information is needed:
- ticket_ready = false
- response = next unanswered troubleshooting question

If enough information exists to create a ticket:
- ticket_ready = true
- resolution_status = "unresolved"
- response = null

If the issue is solved:
- ticket_ready = true
- resolution_status = "resolved"
- response = null
"""

    return ask_llm(prompt)